### ISSUE TITLE
gofish update before gofish init: panic runtime error

### ISSUE THREAD

**Issue by bjornmagnusson** [fishworks/gofish#101]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x7e6c1f]

goroutine 1 [running]:
main.findRigs.func1(0xc04219e560, 0x18, 0x0, 0x0, 0x932b20, 0xc042151b30, 0x20, 0x87f200)
        /go/src/github.com/fishworks/gofish/cmd/gofish/rig_list.go:37 +0x5f
path/filepath.Walk(0xc04219e560, 0x18, 0xc0420e9260, 0x18, 0x8cf8b7)
        /usr/local/go/src/path/filepath/path.go:401 +0x73
main.findRigs(0xc04219e560, 0x18, 0xc04219e560, 0x18, 0xc0420e91e0)
        /go/src/github.com/fishworks/gofish/cmd/gofish/rig_list.go:36 +0xa1
main.updateRigs(0x0, 0x0)
        /go/src/github.com/fishworks/gofish/cmd/gofish/update.go:29 +0x9f
main.newUpdateCmd.func1(0xc0421b2500, 0xb954e0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/fishworks/gofish/cmd/gofish/update.go:20 +0x29
github.com/fishworks/gofish/vendor/github.com/spf13/cobra.(*Command).execute(0xc0421b2500, 0xb954e0, 0x0, 0x0, 0xc0421b2500, 0xb954e0)
        /go/src/github.com/fishworks/gofish/vendor/github.com/spf13/cobra/command.go:756 +0x46f
github.com/fishworks/gofish/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0421a4a00, 0xc0421b2500, 0xc0421b2780, 0xc0421b2a00)
        /go/src/github.com/fishworks/gofish/vendor/github.com/spf13/cobra/command.go:846 +0x311
github.com/fishworks/gofish/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0421a4a00, 0xc042085f78, 0xc042054058)
        /go/src/github.com/fishworks/gofish/vendor/github.com/spf13/cobra/command.go:794 +0x32
main.main()
        /go/src/github.com/fishworks/gofish/cmd/gofish/gofish.go:61 +0x47
```

gofish version: v0.7.0

**Comment by bacongobbler** [comment]
can you try #102 and see if that fixes the issue? Thanks!

**Comment by bacongobbler** [comment]
From initial testing it looks like this has been patched up but let me know if we need to re-open. Thanks!

**Comment by bjornmagnusson** [comment]
Yes, it works!
